#!/usr/bin/env bash
set -euo pipefail

# ============================================================
# Deploys the osm2ohm EMR cluster via Terraform.
# Usage:
#   ./deploy_emr.sh                       -> apply (create cluster + auto-run)
#   ./deploy_emr.sh apply                 -> same as above
#   ./deploy_emr.sh plan                  -> preview terraform changes
#   ./deploy_emr.sh destroy               -> tear down the cluster
#   ./deploy_emr.sh run                   -> re-upload scripts and add a step
#   ./deploy_emr.sh status                -> show the latest step state
#   ./deploy_emr.sh logs   [cluster_id]   -> tail live (alive) or dump from S3
#   ./deploy_emr.sh errors [cluster_id]   -> grep ERROR/Exception in S3 logs
#   ./deploy_emr.sh ls-logs [cluster_id]  -> list all log files in S3
#
# After auto-terminate, pass the cluster_id explicitly if you've run a new
# `apply` that overwrote the terraform state:
#   ./deploy_emr.sh logs   j-XXXXXXX
# ============================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TF_DIR="$SCRIPT_DIR/terraform"

source "$SCRIPT_DIR/.env"

# Region fallback: .env may forget to set/export AWS_DEFAULT_REGION; the
# dataset and cluster live in us-east-1 anyway, so default to that and
# export it so every aws/terraform call sees it.
: "${AWS_DEFAULT_REGION:=us-east-1}"
export AWS_DEFAULT_REGION
export AWS_REGION="$AWS_DEFAULT_REGION"

ACTION="${1:-apply}"
BUCKET="osm2ohm-rub21"

# Keep the cluster alive between steps for iterative testing.
# Set KEEP_CLUSTER_ALIVE=true in .env to disable auto-termination
# and extend the idle timeout to 1h.
TF_EXTRA_VARS=()
if [[ "${KEEP_CLUSTER_ALIVE:-false}" == "true" ]]; then
  TF_EXTRA_VARS+=(-var=auto_terminate_on_completion=false)
  TF_EXTRA_VARS+=(-var=idle_timeout_seconds=3600)
  echo ">> KEEP_CLUSTER_ALIVE=true -> cluster NO se auto-destruye (idle 1h)"
fi

prepare_aws() {
  # NOTE: Skipping `aws emr create-default-roles` because AWS Academy
  # Learner Lab blocks IAM operations. We rely on LabRole (service)
  # and EMR_EC2_DefaultRole (instance profile), both pre-created in
  # the sandbox. On a real AWS account, uncomment the line below.
  # aws emr create-default-roles --region "$AWS_DEFAULT_REGION" >/dev/null

  echo ">> Ensuring bucket s3://$BUCKET ..."
  if ! aws s3api head-bucket --bucket "$BUCKET" >/dev/null 2>&1; then
    aws s3 mb "s3://$BUCKET" --region "$AWS_DEFAULT_REGION"
  fi

  echo ">> Uploading bootstrap script to s3://$BUCKET/bootstrap/ ..."
  aws s3 cp "$SCRIPT_DIR/libs.sh" "s3://$BUCKET/bootstrap/libs.sh"

  echo ">> Uploading scripts and rules to s3://$BUCKET/scripts/ ..."
  aws s3 cp "$SCRIPT_DIR/extract_ohm_candidates.py" "s3://$BUCKET/scripts/extract_ohm_candidates.py"
  aws s3 cp "$SCRIPT_DIR/rules.json" "s3://$BUCKET/scripts/rules.json"
}

cluster_id() {
  cd "$TF_DIR"
  terraform output -raw cluster_id
}

master_dns() {
  cd "$TF_DIR"
  terraform output -raw master_dns
}

key_path() {
  # The .pem is generated by Terraform inside $TF_DIR. Use the absolute path
  # so SSH works no matter the cwd we were invoked from.
  echo "$TF_DIR/emr-key.pem"
}

latest_step_id() {
  local cid="$1"
  aws emr list-steps --cluster-id "$cid" \
    --query 'Steps[0].Id' --output text
}

echo ">> Verifying credentials (region: $AWS_DEFAULT_REGION) ..."
aws sts get-caller-identity | jq -r '"  Account: \(.Account)\n  User:    \(.Arn)"'

case "$ACTION" in
  apply)
    cd "$TF_DIR"
    echo ">> terraform init ..."
    terraform init -input=false
    echo ">> terraform apply ..."
    prepare_aws
    terraform apply -auto-approve "${TF_EXTRA_VARS[@]}"

    CID=$(terraform output -raw cluster_id)
    SSH_CMD=$(terraform output -raw ssh_command)
    KEY_PATH=$(terraform output -raw key_path)

    echo ""
    echo "==================================================================="
    echo "Cluster:        $CID"
    echo "Bucket:         s3://$BUCKET"
    echo "Key (.pem):     $KEY_PATH"
    echo "SSH:            $SSH_CMD"
    echo "==================================================================="
    echo "Spark step lanzado automaticamente."
    echo "Ver progreso:   ./deploy_emr.sh logs"
    echo "Estado:         ./deploy_emr.sh status"
    echo ""
    echo "MODO FIRE-AND-FORGET ACTIVO:"
    echo "  El cluster se auto-destruye apenas termine el step."
    echo "  Resultado en: s3://$BUCKET/output/ohm_candidates/"
    echo "  Logs en:      s3://$BUCKET/logs/$CID/steps/"
    echo ""
    echo "Para mantener el cluster vivo (modo iterativo), aplica con:"
    echo "  cd terraform && terraform apply -var=auto_terminate_on_completion=false"
    ;;

  destroy)
    cd "$TF_DIR"
    echo ">> terraform destroy ..."
    terraform destroy -auto-approve
    ;;

  plan)
    cd "$TF_DIR"
    terraform init -input=false >/dev/null
    terraform plan "${TF_EXTRA_VARS[@]}"
    ;;

  run)
    CID=$(cluster_id)
    prepare_aws
    echo ">> Adding step to cluster $CID ..."
    STEP_ID=$(aws emr add-steps --cluster-id "$CID" --steps "$(cat <<EOF
[{
  "Name": "extract-ohm-candidates",
  "ActionOnFailure": "CONTINUE",
  "Jar": "command-runner.jar",
  "Args": [
    "spark-submit",
    "--deploy-mode", "client",
    "s3://$BUCKET/scripts/extract_ohm_candidates.py",
    "--history_uri", "s3a://osm-pds/planet-history/history-latest.orc",
    "--rules_uri",   "s3://$BUCKET/scripts/rules.json",
    "--output_uri",  "s3://$BUCKET/output/ohm_candidates/"
  ]
}]
EOF
)" --query 'StepIds[0]' --output text)
    echo "   step: $STEP_ID"
    echo ">> Tail logs with: ./deploy_emr.sh logs"
    ;;

  status)
    CID=$(cluster_id)
    SID=$(latest_step_id "$CID")
    aws emr describe-step --cluster-id "$CID" --step-id "$SID" \
      --query 'Step.{Id:Id,Name:Name,State:Status.State,Reason:Status.StateChangeReason.Message,Created:Status.Timeline.CreationDateTime,Started:Status.Timeline.StartDateTime,Ended:Status.Timeline.EndDateTime}' \
      --output table
    ;;

  logs)
    # Optional: ./deploy_emr.sh logs <cluster_id>  (in case TF state is gone)
    CID="${2:-$(cluster_id)}"
    SID=$(latest_step_id "$CID")
    STATE=$(aws emr describe-cluster --cluster-id "$CID" \
              --query 'Cluster.Status.State' --output text 2>/dev/null || echo "GONE")

    echo ">> Cluster: $CID  state: $STATE  step: $SID"

    case "$STATE" in
      STARTING|BOOTSTRAPPING|RUNNING|WAITING)
        DNS=$(master_dns)
        KEY=$(key_path)
        echo ">> Tailing /mnt/var/log/hadoop/steps/$SID/{stderr,stdout} on $DNS"
        echo "   (Ctrl-C para salir. Si el step recien arranca, espera ~30s.)"
        ssh -o StrictHostKeyChecking=accept-new -i "$KEY" "hadoop@$DNS" \
          "tail -F /mnt/var/log/hadoop/steps/$SID/stderr /mnt/var/log/hadoop/steps/$SID/stdout 2>/dev/null"
        ;;
      *)
        echo ">> Cluster no esta vivo. Bajando logs desde S3..."
        echo "   s3://$BUCKET/logs/$CID/steps/$SID/"
        echo ""
        echo "================ controller (estado del step) ================"
        aws s3 cp "s3://$BUCKET/logs/$CID/steps/$SID/controller.gz" - 2>/dev/null \
          | gunzip 2>/dev/null || echo "(sin controller.gz aun — los logs se pushean cada ~5 min)"
        echo ""
        echo "================ stderr (driver Spark) ================"
        aws s3 cp "s3://$BUCKET/logs/$CID/steps/$SID/stderr.gz" - 2>/dev/null \
          | gunzip 2>/dev/null || echo "(sin stderr.gz aun)"
        echo ""
        echo "================ stdout ================"
        aws s3 cp "s3://$BUCKET/logs/$CID/steps/$SID/stdout.gz" - 2>/dev/null \
          | gunzip 2>/dev/null || echo "(sin stdout.gz)"
        ;;
    esac
    ;;

  errors)
    # Extract only the interesting lines from the S3 logs.
    CID="${2:-$(cluster_id)}"
    SID=$(latest_step_id "$CID")
    echo ">> Buscando errores en s3://$BUCKET/logs/$CID/steps/$SID/ ..."
    for f in stderr.gz stdout.gz syslog.gz controller.gz; do
      out=$(aws s3 cp "s3://$BUCKET/logs/$CID/steps/$SID/$f" - 2>/dev/null \
              | gunzip 2>/dev/null \
              | grep -E -i "error|exception|failed|fatal|caused by|traceback" \
              | head -100 || true)
      if [[ -n "$out" ]]; then
        echo "==== $f ===="
        echo "$out"
        echo ""
      fi
    done
    ;;

  ls-logs)
    # List what's available in S3 for the latest cluster.
    CID="${2:-$(cluster_id)}"
    echo ">> s3://$BUCKET/logs/$CID/"
    aws s3 ls --recursive "s3://$BUCKET/logs/$CID/" --human-readable
    ;;

  *)
    echo "Unknown action: $ACTION"
    echo "Use: apply | plan | destroy | run | logs | errors | status | ls-logs"
    exit 1
    ;;
esac
